  [[plugins]]
  repo = 'Shougo/dein.vim'

  # auto complemation for if sentence, and more
  [[plugins]]
  repo = 'tpope/vim-endwise'

  # auto complemation for (, { and more.lh
  [[plugins]]
  repo = 'Townk/vim-autoclose'

  [[plugins]]
  repo = 'joshdick/onedark.vim'
  hook_add = '''
    colorscheme onedark
  '''

  [[plugins]]
  repo = 'w0rp/ale'

  # high light the lines that are chenged.
  [[plugins]]
  repo = 'airblade/vim-gitgutter'
  hook_add = '''
    source ~/.config/nvim/plugins/gitgutter.vim
  '''

  # powerful tool for git.
  [[plugins]]
  repo = 'tpope/vim-fugitive'
  hook_add = '''
    source ~/.config/nvim/plugins/fugitive.vim
  '''

  [[plugins]]
  repo = 'Shougo/denite.nvim'
  hook_add = '''
    source ~/.config/nvim/plugins/denite.vim
  '''

  [[plugins]]
  repo = 'osyo-manga/vim-anzu'
  hook_add = '''
    source ~/.config/nvim/plugins/anzu.vim
  '''

  [[plugins]]
  repo = 'tpope/vim-repeat'
  
  #----NERDTree ------------#
  [[plugins]] 
  repo = 'scrooloose/nerdtree'
  hook_add = '''
   source ~/.config/nvim/plugins/nerdtree.vim
  '''
  #-----end of NERDTree-----#

  [[plugins]]
  repo = 'tpope/vim-surround'
  ###### markdown setting ######
  [[plugins]]
  repo = 'plasticboy/vim-markdown'
  hook_add = '''
    source ~/.config/nvim/plugins/vim-markdown.vim
  '''
  [[plugins]]
  repo = 'kannokanno/previm'
  ###############################

  #---- Latex --------------#
  [[plugins]]
  repo = 'lervag/vimtex'
  on_ft = ['tex']
  hook_add = '''
    source ~/.config/nvim/plugins/vimtex.vim
  '''
  #-------------------------#
  #----Japanese Input ------#
  #-------------------------#
